spring:
  application:
    name: assessment
  datasource:
    url: jdbc:h2:mem:assessment
    #the username and password should be changed if this ever get used more as in a test
    username: sa
    password: sadev
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
assessment:
  csvPath: sample-input.csv
  originalCsvPath: sample-input_original.csv
  copyOriginalFile: true
  datasourceType: csv