spring:
  application:
    name: assessment
  datasource:
    url: jdbc:h2:mem:assessment
    username: sa
    password: sadev
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
assessment:
  csvPath: sample-input.csv
  datasourceType: CSV